// src/lib/components/Toast.svelte
<script lang="ts">
  import { ui } from '$lib/stores/ui';

  const icons: Record<string, string> = {
    success: '✅',
    error: '❌',
    warning: '⚠️',
    info: 'ℹ️'
  };
</script>

<div class="toast-container">
  {#each $ui.notifications as notification (notification.id)}
    <div class="toast toast-{notification.type} animate-fade-in">
      <span class="toast-icon">{icons[notification.type]}</span>
      <span class="toast-message">{notification.message}</span>
      <button
        class="toast-close"
        onclick={() => ui.dismissNotification(notification.id)}
      >
        ✕
      </button>
    </div>
  {/each}
</div>

<style>
  .toast-container {
    position: fixed;
    bottom: 20px;
    right: 20px;
    display: flex;
    flex-direction: column;
    gap: 8px;
    z-index: 300;
    max-width: 400px;
  }

  .toast {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 12px 16px;
    border-radius: var(--radius-md);
    background: var(--tn-bg-float);
    border: 1px solid var(--tn-border);
    box-shadow: var(--shadow-lg);
    font-size: 13px;
    color: var(--tn-fg);
    backdrop-filter: blur(10px);
  }

  .toast-success { border-left: 3px solid var(--tn-green); }
  .toast-error   { border-left: 3px solid var(--tn-red); }
  .toast-warning { border-left: 3px solid var(--tn-yellow); }
  .toast-info    { border-left: 3px solid var(--tn-blue); }

  .toast-icon { font-size: 16px; flex-shrink: 0; }
  .toast-message { flex: 1; }

  .toast-close {
    background: none;
    border: none;
    color: var(--tn-fg-muted);
    cursor: pointer;
    font-size: 12px;
    padding: 2px 4px;
    border-radius: 4px;
    transition: color var(--transition-fast);
  }

  .toast-close:hover {
    color: var(--tn-fg);
  }
</style>

// src/components/Toast.tsx
import { motion, AnimatePresence } from 'framer-motion';
import { CheckCircle2, AlertCircle, Info, AlertTriangle, X } from 'lucide-react';
import { useStore } from '../stores/useStore';

const config = {
  success: { icon: <CheckCircle2 size={16} />, bg: 'bg-tn-green/10 border-tn-green/30', text: 'text-tn-green' },
  error:   { icon: <AlertCircle size={16} />,  bg: 'bg-tn-red/10 border-tn-red/30',     text: 'text-tn-red' },
  info:    { icon: <Info size={16} />,          bg: 'bg-tn-blue/10 border-tn-blue/30',   text: 'text-tn-blue' },
  warning: { icon: <AlertTriangle size={16} />, bg: 'bg-tn-yellow/10 border-tn-yellow/30', text: 'text-tn-yellow' },
};

export function Toast() {
  const { notifications, dismissNotification } = useStore();

  return (
    <div className="fixed bottom-4 right-4 z-[80] flex flex-col gap-2 max-w-sm">
      <AnimatePresence mode="popLayout">
        {notifications.map(n => {
          const c = config[n.type];
          return (
            <motion.div
              key={n.id}
              layout
              initial={{ opacity: 0, y: 20, scale: 0.95, x: 40 }}
              animate={{ opacity: 1, y: 0, scale: 1, x: 0 }}
              exit={{ opacity: 0, scale: 0.9, x: 40 }}
              transition={{ type: 'spring', stiffness: 400, damping: 30 }}
              className={`flex items-center gap-3 rounded-xl border px-4 py-3 shadow-2xl backdrop-blur-xl ${c.bg}`}
            >
              <span className={c.text}>{c.icon}</span>
              <span className="flex-1 text-sm font-medium text-tn-fg">{n.message}</span>
              <button onClick={() => dismissNotification(n.id)} className="shrink-0 rounded-md p-0.5 text-tn-fg-muted hover:text-tn-fg">
                <X size={14} />
              </button>
            </motion.div>
          );
        })}
      </AnimatePresence>
    </div>
  );
}
