// src/components/EmailList.tsx
import { useMemo, useRef, useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Star, Paperclip, CheckSquare, Square, Minus, ArrowUpDown, Inbox } from 'lucide-react';
import { useStore } from '../stores/useStore';
import { ContextMenu, useContextMenu } from './ContextMenu';

function formatDate(date: Date): string {
  const now = new Date();
  const diff = now.getTime() - date.getTime();
  const days = Math.floor(diff / 86400000);
  if (days === 0) return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  if (days === 1) return 'Yesterday';
  if (days < 7) return date.toLocaleDateString([], { weekday: 'short' });
  if (date.getFullYear() === now.getFullYear()) return date.toLocaleDateString([], { month: 'short', day: 'numeric' });
  return date.toLocaleDateString([], { month: 'short', day: 'numeric', year: '2-digit' });
}
function formatSize(b: number) { return b < 1024 ? `${b} B` : b < 1048576 ? `${(b / 1024).toFixed(0)} KB` : `${(b / 1048576).toFixed(1)} MB`; }

export function EmailList() {
  const {
    emails, selectedIds, activeEmail, searchQuery, sortOrder,
    toggleSelect, selectAll, deselectAll, setActiveEmail, toggleStar,
    setSortOrder, isLoading, activeLabel
  } = useStore();

  const { menu, openMenu, closeMenu } = useContextMenu();
  const listRef = useRef<HTMLDivElement>(null);
  const [focusIndex, setFocusIndex] = useState(-1);

  const filteredEmails = useMemo(() => {
    if (!searchQuery) return emails;
    const q = searchQuery.toLowerCase();
    return emails.filter(e =>
      e.subject.toLowerCase().includes(q) || e.snippet.toLowerCase().includes(q) ||
      e.from.name.toLowerCase().includes(q) || e.from.email.toLowerCase().includes(q)
    );
  }, [emails, searchQuery]);

  // Keyboard navigation (j/k or arrow up/down)
  useEffect(() => {
    const handleKey = (e: KeyboardEvent) => {
      const target = e.target as HTMLElement;
      if (target.tagName === 'INPUT' || target.tagName === 'TEXTAREA') return;

      if (e.key === 'j' || e.key === 'ArrowDown') {
        e.preventDefault();
        setFocusIndex(i => Math.min(i + 1, filteredEmails.length - 1));
      }
      if (e.key === 'k' || e.key === 'ArrowUp') {
        e.preventDefault();
        setFocusIndex(i => Math.max(i - 1, 0));
      }
      if (e.key === 'Enter' && focusIndex >= 0 && focusIndex < filteredEmails.length) {
        setActiveEmail(filteredEmails[focusIndex]);
      }
      if (e.key === 'x' && focusIndex >= 0 && focusIndex < filteredEmails.length) {
        toggleSelect(filteredEmails[focusIndex].id);
      }
      if (e.key === 's' && focusIndex >= 0 && focusIndex < filteredEmails.length) {
        toggleStar(filteredEmails[focusIndex].id);
      }
    };
    window.addEventListener('keydown', handleKey);
    return () => window.removeEventListener('keydown', handleKey);
  }, [focusIndex, filteredEmails, setActiveEmail, toggleSelect, toggleStar]);

  // Scroll focused into view
  useEffect(() => {
    if (focusIndex >= 0 && listRef.current) {
      const el = listRef.current.children[focusIndex] as HTMLElement;
      el?.scrollIntoView({ block: 'nearest', behavior: 'smooth' });
    }
  }, [focusIndex]);

  const allSelected = filteredEmails.length > 0 && selectedIds.size === filteredEmails.length;
  const someSelected = selectedIds.size > 0 && !allSelected;

  const labelNames: Record<string, string> = {
    INBOX: 'Inbox', STARRED: 'Starred', SENT: 'Sent', DRAFT: 'Drafts',
    SPAM: 'Spam', TRASH: 'Trash', IMPORTANT: 'Important',
  };

  if (isLoading) {
    return (
      <div className="flex-1 overflow-y-auto p-2 space-y-1">
        {Array.from({ length: 10 }).map((_, i) => (
          <div key={i} className="rounded-xl p-3.5 animate-fade-up" style={{ animationDelay: `${i * 50}ms` }}>
            <div className="flex items-center gap-3">
              <div className="skeleton h-4 w-4 rounded" />
              <div className="skeleton h-7 w-7 rounded-full" />
              <div className="skeleton h-4 w-28 rounded" />
              <div className="skeleton ml-auto h-3 w-14 rounded" />
            </div>
            <div className="ml-14 mt-2 space-y-1.5">
              <div className="skeleton h-3.5 w-3/4 rounded" />
              <div className="skeleton h-3 w-full rounded" />
            </div>
          </div>
        ))}
      </div>
    );
  }

  if (filteredEmails.length === 0) {
    return (
      <div className="flex flex-1 flex-col items-center justify-center p-8 text-center">
        <div className="mb-4 flex h-20 w-20 items-center justify-center rounded-3xl bg-tn-bg-highlight">
          {searchQuery ? <span className="text-3xl">🔍</span> : <Inbox size={32} className="text-tn-fg-muted" />}
        </div>
        <h3 className="text-base font-bold text-tn-fg">{searchQuery ? 'No results' : `${labelNames[activeLabel] || activeLabel} is empty`}</h3>
        <p className="mt-1 text-sm text-tn-fg-muted">{searchQuery ? `Nothing matches "${searchQuery}"` : 'No emails here yet'}</p>
      </div>
    );
  }

  return (
    <div className="flex flex-1 flex-col overflow-hidden">
      {/* Toolbar */}
      <div className="flex items-center gap-2 border-b border-tn-border px-3 py-1.5">
        <button onClick={() => allSelected ? deselectAll() : selectAll()} className="flex items-center rounded-md p-1 text-tn-fg-muted hover:text-tn-fg">
          {allSelected ? <CheckSquare size={15} className="text-tn-blue" /> : someSelected ? <Minus size={15} className="text-tn-blue" /> : <Square size={15} />}
        </button>
        {selectedIds.size > 0 && <span className="rounded-full bg-tn-blue/20 px-2 py-0.5 text-[10px] font-semibold text-tn-blue">{selectedIds.size}</span>}
        <div className="flex-1" />
        <span className="text-[10px] text-tn-fg-muted">{filteredEmails.length} email{filteredEmails.length !== 1 ? 's' : ''}</span>
        <div className="flex items-center">
          <ArrowUpDown size={11} className="text-tn-fg-muted mr-1" />
          <select value={sortOrder} onChange={e => setSortOrder(e.target.value as typeof sortOrder)}
            className="bg-transparent text-[10px] text-tn-fg-muted outline-none cursor-pointer">
            <option value="newest">Newest</option><option value="oldest">Oldest</option>
            <option value="sender">Sender</option><option value="subject">Subject</option>
          </select>
        </div>
      </div>

      {/* Email rows */}
      <div ref={listRef} className="flex-1 overflow-y-auto">
        <AnimatePresence>
          {filteredEmails.map((email, index) => {
            const isActive = activeEmail?.id === email.id;
            const isSelected = selectedIds.has(email.id);
            const isFocused = index === focusIndex;
            return (
              <motion.div
                key={email.id}
                initial={{ opacity: 0, x: -6 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: 6, height: 0 }}
                transition={{ duration: 0.15, delay: Math.min(index * 0.012, 0.2) }}
                onClick={() => { setActiveEmail(email); setFocusIndex(index); }}
                onContextMenu={(e) => openMenu(e, email.id)}
                className={`group relative flex cursor-pointer items-start gap-2.5 border-b border-tn-border/20 px-3 py-3 transition-all duration-100 ${
                  isActive ? 'bg-tn-blue/10 border-l-2 !border-l-tn-blue' :
                  isFocused ? 'bg-tn-bg-highlight/60 ring-1 ring-inset ring-tn-blue/20' :
                  isSelected ? 'bg-tn-selection/40' :
                  email.isRead ? 'hover:bg-tn-bg-highlight/30' : 'bg-tn-bg-dark/20 hover:bg-tn-bg-highlight/30'
                }`}
              >
                {/* Unread dot */}
                {!email.isRead && <div className="absolute left-1 top-1/2 h-2 w-2 -translate-y-1/2 rounded-full bg-tn-blue shadow-sm shadow-tn-blue/50" />}

                {/* Checkbox */}
                <button onClick={e => { e.stopPropagation(); toggleSelect(email.id); }}
                  className="mt-1 shrink-0 text-tn-fg-muted hover:text-tn-fg">
                  {isSelected ? <CheckSquare size={15} className="text-tn-blue" /> : <Square size={15} className="opacity-0 group-hover:opacity-100 transition-opacity" />}
                </button>

                {/* Star */}
                <button onClick={e => { e.stopPropagation(); toggleStar(email.id); }} className="mt-1 shrink-0">
                  <Star size={14} className={email.isStarred ? 'fill-tn-yellow text-tn-yellow' : 'text-tn-fg-gutter hover:text-tn-yellow transition-colors'} />
                </button>

                {/* Content */}
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2">
                    <div className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-[10px] font-bold ${
                      isActive ? 'bg-tn-blue/20 text-tn-blue' : 'bg-gradient-to-br from-tn-purple/20 to-tn-blue/20 text-tn-fg-dark'
                    }`}>
                      {email.from.name.charAt(0)}
                    </div>
                    <span className={`flex-1 truncate text-sm ${email.isRead ? 'text-tn-fg-dark' : 'font-semibold text-tn-fg'}`}>
                      {email.from.name}
                    </span>
                    {email.hasAttachments && <Paperclip size={11} className="shrink-0 text-tn-fg-muted" />}
                    <span className="shrink-0 text-[10px] text-tn-fg-muted">{formatDate(email.date)}</span>
                  </div>
                  <p className={`truncate text-xs mt-0.5 ${email.isRead ? 'text-tn-fg-muted' : 'text-tn-fg-dark font-medium'}`}>{email.subject}</p>
                  <p className="truncate text-[11px] text-tn-fg-muted/60 mt-0.5">{email.snippet}</p>
                  {email.hasAttachments && email.attachments.length > 0 && (
                    <div className="mt-1.5 flex items-center gap-1">
                      <span className="rounded-md bg-tn-bg-highlight/50 px-2 py-0.5 text-[9px] text-tn-fg-muted border border-tn-border/20">
                        📎 {email.attachments[0].filename}{email.attachments.length > 1 ? ` +${email.attachments.length - 1}` : ''} ({formatSize(email.attachments[0].size)})
                      </span>
                    </div>
                  )}
                </div>
              </motion.div>
            );
          })}
        </AnimatePresence>
      </div>

      {/* Context Menu */}
      <ContextMenu x={menu.x} y={menu.y} emailId={menu.emailId} onClose={closeMenu} />
    </div>
  );
}

// src/lib/components/EmailList.svelte
<script lang="ts">
  import { emailStore, selectedCount, hasSelection, allSelected } from '$lib/stores/emails';
  import { ui } from '$lib/stores/ui';
  import LoadingSpinner from './LoadingSpinner.svelte';
  import type { Email } from '$lib/types';

  function formatDate(date: Date): string {
    const now = new Date();
    const diff = now.getTime() - date.getTime();
    const days = Math.floor(diff / (1000 * 60 * 60 * 24));

    if (days === 0) {
      return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    } else if (days === 1) {
      return 'Yesterday';
    } else if (days < 7) {
      return date.toLocaleDateString([], { weekday: 'short' });
    } else if (days < 365) {
      return date.toLocaleDateString([], { month: 'short', day: 'numeric' });
    }
    return date.toLocaleDateString([], { year: 'numeric', month: 'short', day: 'numeric' });
  }

  function formatSize(bytes: number): string {
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  }

  function selectEmail(email: Email) {
    emailStore.setActiveEmail(email);
  }

  function toggleSelectAll() {
    if ($allSelected) {
      emailStore.deselectAll();
    } else {
      emailStore.selectAll();
    }
  }

  // Quick select helpers
  function selectAllRead() {
    emailStore.selectByFilter(e => e.isRead);
  }

  function selectAllUnread() {
    emailStore.selectByFilter(e => !e.isRead);
  }
</script>

<div class="email-list-container">
  <!-- Selection toolbar -->
  <div class="list-toolbar">
    <label class="select-all">
      <input
        type="checkbox"
        checked={$allSelected}
        indeterminate={$hasSelection && !$allSelected}
        onchange={toggleSelectAll}
      />
      {#if $hasSelection}
        <span class="selected-count">{$selectedCount} selected</span>
      {:else}
        <span>Select all</span>
      {/if}
    </label>

    <div class="quick-select">
      <button onclick={selectAllRead}>Read</button>
      <button onclick={selectAllUnread}>Unread</button>
    </div>

    <span class="email-count">
      {$emailStore.emails.length} of ~{$emailStore.pagination.totalEstimate} emails
    </span>
  </div>

  <!-- Bulk progress bar -->
  {#if $emailStore.isBulkProcessing}
    <div class="bulk-progress">
      <div class="progress-bar">
        <div
          class="progress-fill"
          style="width: {($emailStore.bulkProgress.current / $emailStore.bulkProgress.total) * 100}%"
        ></div>
      </div>
      <span class="progress-text">
        Processing {$emailStore.bulkProgress.current} / {$emailStore.bulkProgress.total}
      </span>
    </div>
  {/if}

  <!-- Email list -->
  <div class="email-list">
    {#if $emailStore.isLoading}
      <div class="loading-state">
        <LoadingSpinner size={32} />
        <span>Loading emails...</span>
      </div>
    {:else if $emailStore.emails.length === 0}
      <div class="empty-state">
        <span class="empty-icon">📭</span>
        <h3>No emails found</h3>
        <p>Try adjusting your search or filters</p>
      </div>
    {:else}
      {#each $emailStore.emails as email (email.id)}
        <button
          class="email-row"
          class:unread={!email.isRead}
          class:selected={$emailStore.selectedIds.has(email.id)}
          class:active={$emailStore.activeEmail?.id === email.id}
          onclick={() => selectEmail(email)}
        >
          <label class="email-checkbox" onclick={(e) => e.stopPropagation()}>
            <input
              type="checkbox"
              checked={$emailStore.selectedIds.has(email.id)}
              onchange={() => emailStore.toggleSelect(email.id)}
            />
          </label>

          <div class="email-star" class:starred={email.isStarred}>
            {email.isStarred ? '⭐' : '☆'}
          </div>

          <div class="email-content">
            <div class="email-top-row">
              <span class="email-from" class:unread={!email.isRead}>
                {email.from.name || email.from.email}
              </span>
              <div class="email-meta">
                {#if email.hasAttachments}
                  <span class="attachment-icon" title="Has attachments">📎</span>
                {/if}
                {#if email.isImportant}
                  <span class="important-icon" title="Important">🏷️</span>
                {/if}
                <span class="email-size">{formatSize(email.sizeEstimate)}</span>
                <span class="email-date">{formatDate(email.date)}</span>
              </div>
            </div>
            <div class="email-subject" class:unread={!email.isRead}>
              {email.subject}
            </div>
            <div class="email-snippet">{email.snippet}</div>
          </div>
        </button>
      {/each}

      <!-- Load more -->
      {#if $emailStore.pagination.nextPageToken}
        <button class="load-more-btn" onclick={() => {
          // Load next page logic would go here
        }}>
          Load more emails...
        </button>
      {/if}
    {/if}
  </div>
</div>

<style>
  .email-list-container {
    display: flex;
    flex-direction: column;
    height: 100%;
    min-width: 400px;
    border-right: 1px solid var(--tn-border);
  }

  .list-toolbar {
    display: flex;
    align-items: center;
    gap: 12px;
    padding: 8px 16px;
    border-bottom: 1px solid var(--tn-border);
    background: var(--tn-bg-dark);
    font-size: 13px;
  }

  .select-all {
    display: flex;
    align-items: center;
    gap: 8px;
    cursor: pointer;
    color: var(--tn-fg-dark);
  }

  .select-all input {
    accent-color: var(--tn-blue);
  }

  .selected-count {
    color: var(--tn-blue);
    font-weight: 600;
  }

  .quick-select {
    display: flex;
    gap: 4px;
  }

  .quick-select button {
    padding: 3px 10px;
    border: 1px solid var(--tn-border);
    border-radius: 12px;
    background: none;
    color: var(--tn-fg-muted);
    font-size: 11px;
    cursor: pointer;
    transition: all var(--transition-fast);
  }

  .quick-select button:hover {
    background: var(--tn-bg-highlight);
    color: var(--tn-fg);
  }

  .email-count {
    margin-left: auto;
    color: var(--tn-fg-muted);
    font-size: 12px;
  }

  /* Bulk progress */
  .bulk-progress {
    padding: 8px 16px;
    background: var(--tn-bg-highlight);
    border-bottom: 1px solid var(--tn-border);
  }

  .progress-bar {
    height: 4px;
    background: var(--tn-bg);
    border-radius: 2px;
    overflow: hidden;
    margin-bottom: 4px;
  }

  .progress-fill {
    height: 100%;
    background: linear-gradient(90deg, var(--tn-blue), var(--tn-purple));
    border-radius: 2px;
    transition: width 200ms ease;
  }

  .progress-text {
    font-size: 11px;
    color: var(--tn-fg-muted);
  }

  /* Email list */
  .email-list {
    flex: 1;
    overflow-y: auto;
    overflow-x: hidden;
  }

  .email-row {
    display: flex;
    align-items: flex-start;
    gap: 8px;
    padding: 12px 16px;
    border: none;
    border-bottom: 1px solid rgba(59, 66, 97, 0.3);
    background: none;
    cursor: pointer;
    transition: background var(--transition-fast);
    width: 100%;
    text-align: left;
  }

  .email-row:hover {
    background: var(--tn-bg-highlight);
  }

  .email-row.active {
    background: var(--tn-selection);
    border-left: 3px solid var(--tn-blue);
  }

  .email-row.selected {
    background: rgba(122, 162, 247, 0.08);
  }

  .email-row.unread {
    background: rgba(122, 162, 247, 0.03);
  }

  .email-checkbox {
    padding-top: 2px;
    cursor: pointer;
    flex-shrink: 0;
  }

  .email-checkbox input {
    accent-color: var(--tn-blue);
  }

  .email-star {
    padding-top: 2px;
    font-size: 14px;
    flex-shrink: 0;
    opacity: 0.3;
    cursor: pointer;
    transition: opacity var(--transition-fast);
  }

  .email-star.starred,
  .email-star:hover {
    opacity: 1;
  }

  .email-content {
    flex: 1;
    min-width: 0;
    display: flex;
    flex-direction: column;
    gap: 2px;
  }

  .email-top-row {
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 8px;
  }

  .email-from {
    font-size: 13px;
    color: var(--tn-fg-dark);
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .email-from.unread {
    font-weight: 700;
    color: var(--tn-fg);
  }

  .email-meta {
    display: flex;
    align-items: center;
    gap: 6px;
    flex-shrink: 0;
  }

  .attachment-icon, .important-icon {
    font-size: 12px;
  }

  .email-size {
    font-size: 11px;
    color: var(--tn-fg-muted);
  }

  .email-date {
    font-size: 12px;
    color: var(--tn-fg-muted);
    white-space: nowrap;
  }

  .email-subject {
    font-size: 13px;
    color: var(--tn-fg-dark);
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .email-subject.unread {
    font-weight: 600;
    color: var(--tn-fg);
  }

  .email-snippet {
    font-size: 12px;
    color: var(--tn-fg-muted);
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  /* States */
  .loading-state, .empty-state {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 300px;
    gap: 12px;
    color: var(--tn-fg-muted);
  }

  .empty-icon {
    font-size: 48px;
  }

  .empty-state h3 {
    font-size: 16px;
    color: var(--tn-fg-dark);
  }

  .empty-state p {
    font-size: 13px;
  }

  .load-more-btn {
    width: 100%;
    padding: 16px;
    border: none;
    background: var(--tn-bg-highlight);
    color: var(--tn-blue);
    font-size: 14px;
    cursor: pointer;
    transition: background var(--transition-fast);
  }

  .load-more-btn:hover {
    background: var(--tn-selection);
  }
</style>
