// src/components/SearchBar.tsx
import { useState, useRef, useEffect } from 'react';
import { Search, X, SlidersHorizontal, Filter } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { useStore } from '../stores/useStore';

const quickFilters = [
  { label: 'Unread', query: 'is:unread', color: 'bg-tn-blue/15 text-tn-blue border-tn-blue/20' },
  { label: 'Attachments', query: 'has:attachment', color: 'bg-tn-purple/15 text-tn-purple border-tn-purple/20' },
  { label: 'Starred', query: 'is:starred', color: 'bg-tn-yellow/15 text-tn-yellow border-tn-yellow/20' },
  { label: 'Older 1yr', query: 'older_than:1y', color: 'bg-tn-orange/15 text-tn-orange border-tn-orange/20' },
  { label: 'Large (5MB+)', query: 'larger:5M', color: 'bg-tn-red/15 text-tn-red border-tn-red/20' },
  { label: 'Newsletters', query: 'from:noreply', color: 'bg-tn-teal/15 text-tn-teal border-tn-teal/20' },
];

export function SearchBar() {
  const { searchQuery, setSearchQuery, emails, selectByFilter } = useStore();
  const [localQuery, setLocalQuery] = useState(searchQuery);
  const [showFilters, setShowFilters] = useState(false);
  const [isFocused, setIsFocused] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => { setLocalQuery(searchQuery); }, [searchQuery]);

  const handleSearch = (query: string) => { setSearchQuery(query); setLocalQuery(query); };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') handleSearch(localQuery);
    if (e.key === 'Escape') { setLocalQuery(''); handleSearch(''); inputRef.current?.blur(); }
  };

  const filteredCount = searchQuery
    ? emails.filter(e => e.subject.toLowerCase().includes(searchQuery.toLowerCase()) ||
        e.snippet.toLowerCase().includes(searchQuery.toLowerCase()) ||
        e.from.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        e.from.email.toLowerCase().includes(searchQuery.toLowerCase())).length
    : emails.length;

  return (
    <div className="relative">
      <div className="flex items-center gap-2">
        <div className={`flex flex-1 items-center gap-2 rounded-xl border bg-tn-bg-highlight/60 px-3 py-2 transition-all duration-200 ${
          isFocused ? 'border-tn-blue/40 bg-tn-bg-highlight shadow-sm shadow-tn-blue/10' : 'border-tn-border/50'
        }`}>
          <Search size={14} className="shrink-0 text-tn-fg-muted" />
          <input ref={inputRef} type="text" placeholder="Search emails... ( / )"
            value={localQuery} onChange={e => setLocalQuery(e.target.value)}
            onKeyDown={handleKeyDown} onFocus={() => setIsFocused(true)} onBlur={() => setIsFocused(false)}
            className="flex-1 bg-transparent text-sm text-tn-fg placeholder-tn-fg-muted/50 outline-none" />
          {localQuery && (
            <button onClick={() => { setLocalQuery(''); handleSearch(''); }} className="shrink-0 rounded-md p-0.5 text-tn-fg-muted hover:text-tn-fg">
              <X size={13} />
            </button>
          )}
          {searchQuery && <span className="shrink-0 rounded-full bg-tn-blue/20 px-2 py-0.5 text-[9px] font-semibold text-tn-blue">{filteredCount}</span>}
        </div>
        <button onClick={() => setShowFilters(!showFilters)}
          className={`flex h-9 w-9 items-center justify-center rounded-xl border transition-all ${
            showFilters ? 'border-tn-blue/40 bg-tn-blue/10 text-tn-blue' : 'border-tn-border/50 bg-tn-bg-highlight/60 text-tn-fg-muted hover:text-tn-fg'
          }`}>
          <SlidersHorizontal size={14} />
        </button>
      </div>

      <AnimatePresence>
        {showFilters && (
          <motion.div initial={{ opacity: 0, y: -6, height: 0 }} animate={{ opacity: 1, y: 0, height: 'auto' }}
            exit={{ opacity: 0, y: -6, height: 0 }} className="mt-2 overflow-hidden rounded-xl border border-tn-border bg-tn-bg-dark p-3">
            <div className="mb-2 flex items-center gap-2 text-[10px] font-semibold uppercase tracking-wider text-tn-fg-muted">
              <Filter size={10} /> Quick Filters
            </div>
            <div className="flex flex-wrap gap-1.5">
              {quickFilters.map(f => (
                <button key={f.label} onClick={() => { handleSearch(f.query); setShowFilters(false); }}
                  className={`rounded-lg border px-2.5 py-1 text-[11px] font-medium transition-all hover:scale-105 ${f.color}`}>
                  {f.label}
                </button>
              ))}
            </div>
            <div className="mt-2.5 flex gap-1.5">
              <button onClick={() => selectByFilter(e => !e.isRead)}
                className="rounded-lg bg-tn-bg-highlight px-2.5 py-1 text-[10px] text-tn-fg-dark hover:bg-tn-bg-float transition-colors">Select unread</button>
              <button onClick={() => selectByFilter(() => true)}
                className="rounded-lg bg-tn-bg-highlight px-2.5 py-1 text-[10px] text-tn-fg-dark hover:bg-tn-bg-float transition-colors">Select all</button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

// src/lib/components/SearchBar.svelte
<script lang="ts">
  import { filters, gmailQuery } from '$lib/stores/filters';
  import { emailStore } from '$lib/stores/emails';
  import { ui } from '$lib/stores/ui';
  import { fetchEmails } from '$lib/services/gmailService';

  let searchInput = '';
  let showAdvanced = false;
  let fromFilter = '';
  let readFilter: 'all' | 'read' | 'unread' = 'all';
  let hasAttachment = false;
  let sizeFilter = '';

  async function handleSearch() {
    filters.setQuery(searchInput);
    filters.setFrom(fromFilter);
    filters.setReadFilter(readFilter === 'all' ? null : readFilter === 'read');
    filters.setAttachmentFilter(hasAttachment || null);
    filters.setSizeFilter(sizeFilter ? parseInt(sizeFilter) * 1024 * 1024 : null); // MB to bytes

    const query = $gmailQuery;
    await fetchEmails($emailStore.activeLabel, query);
  }

  function clearSearch() {
    searchInput = '';
    fromFilter = '';
    readFilter = 'all';
    hasAttachment = false;
    sizeFilter = '';
    filters.reset();
    fetchEmails($emailStore.activeLabel);
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Enter') handleSearch();
    if (e.key === 'Escape') clearSearch();
  }

  // Quick filters
  const quickFilters = [
    { label: 'Unread', query: 'is:unread', icon: '🔵' },
    { label: 'Has attachments', query: 'has:attachment', icon: '📎' },
    { label: 'Older than 1 year', query: 'older_than:1y', icon: '📅' },
    { label: 'Large emails', query: 'larger:5M', icon: '📦' },
    { label: 'Newsletters', query: 'category:promotions', icon: '📰' },
    { label: 'Social', query: 'category:social', icon: '👥' },
  ];

  async function applyQuickFilter(query: string) {
    searchInput = query;
    filters.setQuery(query);
    await fetchEmails($emailStore.activeLabel, query);
  }
</script>

<div class="search-container">
  <div class="search-main">
    <div class="search-input-wrapper">
      <span class="search-icon">🔍</span>
      <input
        type="text"
        class="search-input"
        placeholder="Search emails... (Gmail syntax supported)"
        bind:value={searchInput}
        onkeydown={handleKeydown}
      />
      {#if searchInput}
        <button class="clear-btn" onclick={clearSearch}>✕</button>
      {/if}
    </div>

    <button class="search-btn" onclick={handleSearch}>Search</button>
    <button
      class="advanced-btn"
      class:active={showAdvanced}
      onclick={() => showAdvanced = !showAdvanced}
      title="Advanced filters"
    >
      ⚙️
    </button>
    <button
      class="bulk-btn"
      onclick={() => ui.toggleBulkPanel()}
      title="Bulk actions"
    >
      ⚡
    </button>
    <button
      class="apps-btn"
      onclick={() => ui.toggleAppLauncher()}
      title="Google Apps"
    >
      ▦
    </button>
  </div>

  {#if showAdvanced}
    <div class="advanced-filters animate-fade-in">
      <div class="filter-row">
        <div class="filter-group">
          <label>From</label>
          <input
            type="text"
            placeholder="sender@example.com"
            bind:value={fromFilter}
          />
        </div>

        <div class="filter-group">
          <label>Read status</label>
          <select bind:value={readFilter}>
            <option value="all">All</option>
            <option value="unread">Unread only</option>
            <option value="read">Read only</option>
          </select>
        </div>

        <div class="filter-group">
          <label>Larger than (MB)</label>
          <input
            type="number"
            placeholder="5"
            bind:value={sizeFilter}
            min="0"
          />
        </div>

        <label class="checkbox-group">
          <input type="checkbox" bind:checked={hasAttachment} />
          <span>Has attachments</span>
        </label>
      </div>
    </div>
  {/if}

  <div class="quick-filters">
    {#each quickFilters as qf}
      <button
        class="quick-filter-chip"
        onclick={() => applyQuickFilter(qf.query)}
      >
        <span>{qf.icon}</span>
        <span>{qf.label}</span>
      </button>
    {/each}
  </div>
</div>

<style>
  .search-container {
    padding: 12px 16px;
    border-bottom: 1px solid var(--tn-border);
    background: var(--tn-bg-dark);
  }

  .search-main {
    display: flex;
    gap: 8px;
    align-items: center;
  }

  .search-input-wrapper {
    flex: 1;
    display: flex;
    align-items: center;
    background: var(--tn-bg);
    border: 1px solid var(--tn-border);
    border-radius: var(--radius-md);
    padding: 0 12px;
    transition: border-color var(--transition-fast);
  }

  .search-input-wrapper:focus-within {
    border-color: var(--tn-blue);
    box-shadow: 0 0 0 3px rgba(122, 162, 247, 0.1);
  }

  .search-icon {
    font-size: 14px;
    margin-right: 8px;
    opacity: 0.5;
  }

  .search-input {
    flex: 1;
    padding: 10px 0;
    border: none;
    background: none;
    color: var(--tn-fg);
    font-size: 14px;
    outline: none;
  }

  .search-input::placeholder {
    color: var(--tn-fg-muted);
  }

  .clear-btn {
    background: none;
    border: none;
    color: var(--tn-fg-muted);
    cursor: pointer;
    padding: 4px;
    font-size: 12px;
    border-radius: 50%;
    transition: all var(--transition-fast);
  }

  .clear-btn:hover {
    background: var(--tn-bg-highlight);
    color: var(--tn-fg);
  }

  .search-btn, .advanced-btn, .bulk-btn, .apps-btn {
    padding: 10px 16px;
    border: 1px solid var(--tn-border);
    border-radius: var(--radius-md);
    background: var(--tn-bg);
    color: var(--tn-fg-dark);
    font-size: 14px;
    cursor: pointer;
    transition: all var(--transition-fast);
    white-space: nowrap;
  }

  .search-btn {
    background: var(--tn-blue);
    border-color: var(--tn-blue);
    color: var(--tn-bg-darker);
    font-weight: 600;
  }

  .search-btn:hover {
    background: #8db0f9;
  }

  .advanced-btn:hover, .bulk-btn:hover, .apps-btn:hover {
    background: var(--tn-bg-highlight);
  }

  .advanced-btn.active {
    background: var(--tn-selection);
    border-color: var(--tn-blue);
  }

  .bulk-btn {
    color: var(--tn-orange);
  }

  .apps-btn {
    font-size: 18px;
    padding: 10px 12px;
  }

  /* Advanced filters */
  .advanced-filters {
    padding: 16px 0 8px;
  }

  .filter-row {
    display: flex;
    gap: 12px;
    align-items: flex-end;
    flex-wrap: wrap;
  }

  .filter-group {
    display: flex;
    flex-direction: column;
    gap: 4px;
    flex: 1;
    min-width: 150px;
  }

  .filter-group label {
    font-size: 11px;
    font-weight: 600;
    color: var(--tn-fg-muted);
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }

  .filter-group input,
  .filter-group select {
    padding: 8px 12px;
    background: var(--tn-bg);
    border: 1px solid var(--tn-border);
    border-radius: var(--radius-sm);
    color: var(--tn-fg);
    font-size: 13px;
    outline: none;
  }

  .filter-group input:focus,
  .filter-group select:focus {
    border-color: var(--tn-blue);
  }

  .checkbox-group {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 13px;
    color: var(--tn-fg-dark);
    cursor: pointer;
    padding-bottom: 8px;
  }

  .checkbox-group input[type="checkbox"] {
    accent-color: var(--tn-blue);
  }

  /* Quick filters */
  .quick-filters {
    display: flex;
    gap: 6px;
    margin-top: 10px;
    flex-wrap: wrap;
  }

  .quick-filter-chip {
    display: flex;
    align-items: center;
    gap: 4px;
    padding: 5px 12px;
    border: 1px solid var(--tn-border);
    border-radius: 20px;
    background: none;
    color: var(--tn-fg-muted);
    font-size: 12px;
    cursor: pointer;
    transition: all var(--transition-fast);
  }

  .quick-filter-chip:hover {
    background: var(--tn-bg-highlight);
    border-color: var(--tn-blue);
    color: var(--tn-blue);
  }
</style>
